### ISSUE TITLE
Edit coverage

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/android-mdm-agent#153]
Hi, @rafaelje 

It is necessary that all the `.html` files of the coverage have the following header:

```
---
layout: coverage
---
```
This is because the Jekyll pages used them to integrate the files into the template.

**Comment by ajsb85** [comment]
Hi, @rafaelje 

I think this task is done.
Could you confirm and close it?

Thanks.

**Comment by rafaelje** [comment]
Yes this task it's done
