### ISSUE TITLE
Edit javadoc

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/android-mdm-agent#154]
Hi, @rafaelje 

It is necessary to change the code generated by Javadoc, currently the returned code is not compatible with our sites in Jekyll. The most advisable thing would be to generate markdown files instead of HTML, but also it would be acceptable to customize the generated HTML.

I am currently researching on the subject so I can help as much as possible. this is the only thing I have found to be moderately useful so far:

- https://github.com/delight-im/Javadoc-to-Markdown/blob/gh-pages/_js/javadoc-to-markdown.js#L4
- https://github.com/todesking/nyandoc

**Comment by Gianfranco97** [comment]
I think this would be the way we have to take
- http://www.filigris.com/docflex-javadoc/
- http://www.filigris.com/docflex/

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 

Lets try by yourself in your local machine or using Travis CI in your fork.
Take the way more faster please.

Thanks.

**Comment by Gianfranco97** [comment]
Currently attempting with:: http://www.javalobby.org/java/forums/t65587.html

**Comment by Gianfranco97** [comment]
the DocWrench project was discontinued and its page is no longer on the air

**Comment by Gianfranco97** [comment]
I'll try it with http://www.jaryard.com/

looks promising

**Comment by Gianfranco97** [comment]
In the end no Doclet or library I found and tried turned out to be useful to meet our requirements. I ended up applying my own solution, a little more manual and less elegant, but at least it meets all our requirements.

**Comment by Gianfranco97** [comment]
## The new steps to generate the documentation are the following:
1. at the moment of running the script to generate the documentation it is necessary to pass the parameter `-nonavbar '
2. You have to add at the beginning of the HTML files the following header: 
```
---
layout: codeDocumentation
---
```
3. delete the `index.html` file
4. rename the `overview-summary.html` file to` index.html`
5. Replace all the content of stylesheet.css with the following: https://gist.github.com/Gianfranco97/1c851a3c008bc1abc9d7560a8787a949

**Comment by ajsb85** [comment]
Hi, @rafaelje 

I think this task is done.
Could you confirm and close it?

Thanks.
