### ISSUE TITLE
Improve images of the Wizard

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-mdm-agent#173]
Hi, @rafaelje 

Could you share with @mmillevoye the source files of the wizard?

Marie, maybe a solid background is better to move between the pages.
And remove the Teclib' logo or use the logo with white background.

And Rafael, btw could you remove the link in the space after the brand name?

![image](https://user-images.githubusercontent.com/663460/32303178-498e76c4-bf67-11e7-9c5b-49322ebc9d3c.png)

**Comment by rafaelje** [comment]
This walkthrough is created with 2 images one with the phone and the other is the component inside the phone, I'll send by email the source image on fireworks png

**Background**
![bg_walkthrough](https://user-images.githubusercontent.com/4085091/32336353-7b41147a-bfc5-11e7-8b0e-54d2f4a2e4bf.png)

**Components**
![logoflyve](https://user-images.githubusercontent.com/4085091/32336530-eaacca8e-bfc5-11e7-9a1b-3eec675fc0fd.png)
![ic_walkthroug_3](https://user-images.githubusercontent.com/4085091/32336425-b434724a-bfc5-11e7-8a0b-f22322911306.png)
![ic_walkthroug_2](https://user-images.githubusercontent.com/4085091/32336426-b5d585d0-bfc5-11e7-8563-14ede16990ac.png)

**Comment by mmillevoye** [comment]
Hi y'all, i need at least an image (if not sources) of the backround with the whole mobile (without the grey part with text upon it. So i can make a proper whole screen backround :)

Thanks

**Comment by rafaelje** [comment]
Hi @mmillevoye this is the mobile image, please let me know if you need something more

![phone](https://user-images.githubusercontent.com/4085091/32808598-fc6b76dc-c969-11e7-83c9-e78035aad0f4.png)

**Comment by mmillevoye** [comment]
![flyve-wizard](https://user-images.githubusercontent.com/29282308/32884914-30a778e4-cabc-11e7-8e32-a1fc1646d593.png)
not sure it's what you need... But that's what i understood ^^

**Comment by mmillevoye** [comment]
<img width="278" alt="capture d ecran 2017-11-16 a 15 47 36" src="https://user-images.githubusercontent.com/29282308/32897317-862b4b0a-cae5-11e7-8e40-14df8ee1623b.png">
And what is that ?

**Comment by ajsb85** [comment]
@mmillevoye This is a proposal of Rafael.
The idea is to create a Wizard to help the user, how to register the MDM Agent.

**Comment by rafaelje** [comment]
@mmillevoye this is the proposal

![screenshot_1510843979](https://user-images.githubusercontent.com/4085091/32897588-6e248a90-cabc-11e7-9f47-5f3cf6889c82.png)
![screenshot_1510843983](https://user-images.githubusercontent.com/4085091/32897590-6e58146e-cabc-11e7-9a8c-cfbab855ec98.png)
![screenshot_1510843987](https://user-images.githubusercontent.com/4085091/32897591-6e738758-cabc-11e7-9205-60ab30173b84.png)

**Comment by ajsb85** [comment]
@mmillevoye Their initial proposal

Screen 1
Information about Flyve MDM

Screen 2
Information about how send and invitation to the user

Screen 3
How to enroll the device from this invitation

So, we can create a HackMD file to discuss the text later.
But these are the main points of each screen.

**Comment by ajsb85** [comment]
@mmillevoye You can propose a new design for this wizard with these 3 main points 👍🏻

**Comment by mmillevoye** [comment]
![flyve-wizard1](https://user-images.githubusercontent.com/29282308/32900566-091f23c6-caee-11e7-91b3-09f473ac0d45.png)
do i keep going on that direction ? We can synthetise the text ?

**Comment by ajsb85** [comment]
@mmillevoye We are using L10N.
So a lot of images for each translation.

**Comment by ajsb85** [comment]
@mmillevoye Maybe, @Rafaelje can add style to the plain text, to look like yuor design in any language

**Comment by mmillevoye** [comment]
How many translations ?

**Comment by mmillevoye** [comment]
because if i have 3 images in 10 translations it's fully doable

**Comment by ajsb85** [comment]
@mmillevoye GLPI is translated to 80 languages

**Comment by mmillevoye** [comment]
ok ^^ i find an other way

**Comment by mmillevoye** [comment]
![flyve-wizard](https://user-images.githubusercontent.com/29282308/32901064-331ad138-caef-11e7-8c30-c48929bd1781.png)
like this no matter how long translations are, they can be in two lines centered. With style on text. Possible ?

**Comment by ajsb85** [comment]
@mmillevoye I think yes @Rafaelje 
👌🏻 i like it

**Comment by mmillevoye** [comment]
ok i go on

**Comment by mmillevoye** [comment]
![flyve-wizard1](https://user-images.githubusercontent.com/29282308/32902264-3a5e535e-caf2-11e7-85d3-01505eb48577.png)
![flyve-wizard2](https://user-images.githubusercontent.com/29282308/32902265-3a76bf7a-caf2-11e7-98b5-0a846dc49962.png)
![flyve-wizard3](https://user-images.githubusercontent.com/29282308/32902266-3a8fb1e2-caf2-11e7-9725-1c8aa802e124.png)
What do u think ?

**Comment by ajsb85** [comment]
@mmillevoye Could you add a button to open another page for the Help Center?

**Comment by mmillevoye** [comment]
ok, in which screen, all of them ?

**Comment by ajsb85** [comment]
@mmillevoye Maybe to persist in all screens (with the Flyve MDM logo), or in the last one.

**Comment by mmillevoye** [comment]
![flyve-wizard-18](https://user-images.githubusercontent.com/29282308/32902892-e3a6ed76-caf3-11e7-8b8c-819e168140cc.png)
![flyve-wizard-19](https://user-images.githubusercontent.com/29282308/32902893-e3c05932-caf3-11e7-8ff7-45655a93d7bf.png)
![flyve-wizard-20](https://user-images.githubusercontent.com/29282308/32902894-e3d2e8e0-caf3-11e7-8113-4c79722815f8.png)

**Comment by ajsb85** [comment]
@mmillevoye 👨🏻‍⚖️

**Comment by rafaelje** [comment]
@mmillevoye can you share with me every piece of this design:

- background
- logo
- step image with text
- More information here image

**Comment by mmillevoye** [comment]
![flyve-wizard-agent-logo](https://user-images.githubusercontent.com/29282308/32905104-5c7c4426-caf9-11e7-9241-90ffb042451a.png)
![flyve-wizard-background](https://user-images.githubusercontent.com/29282308/32905105-5c8f94c2-caf9-11e7-923a-ece3e47c6f88.png)
![flyve-wizard-step1](https://user-images.githubusercontent.com/29282308/32905106-5ca76db8-caf9-11e7-97cb-24bf7f80e40b.png)
![flyve-wizard-step2](https://user-images.githubusercontent.com/29282308/32905107-5cbbde24-caf9-11e7-83cd-ce7f818dd813.png)
![flyve-wizard-step3](https://user-images.githubusercontent.com/29282308/32905108-5cced358-caf9-11e7-8fec-37e33403a872.png)
![flyve-wizard-text-create](https://user-images.githubusercontent.com/29282308/32905109-5ce1f76c-caf9-11e7-9ddb-e1f8427d5d91.png)
![flyve-wizard-text-enroll](https://user-images.githubusercontent.com/29282308/32905110-5cf4916a-caf9-11e7-9ef4-8224854ae288.png)
![flyve-wizard-text-more](https://user-images.githubusercontent.com/29282308/32905111-5d1e4d34-caf9-11e7-9ef5-939b3c9ce3db.png)
![flyve-wizard-text-send](https://user-images.githubusercontent.com/29282308/32905112-5d34da4a-caf9-11e7-9059-db327d2421b5.png)

**Comment by mmillevoye** [comment]
the last 4 are white so... ;)

**Comment by ajsb85** [comment]
Hi, @rafaelje 

Here how looks the new walk-through in the tablet Lenovo.
Also the report of the Inventory  Agent to see details about the screen and resolutions.

[lenovo.json.zip](https://github.com/flyve-mdm/android-mdm-agent/files/1498360/lenovo.json.zip)

![image](https://user-images.githubusercontent.com/663460/33163425-ba9097da-d02e-11e7-9680-3ab150f7f5ac.png)

**Comment by ajsb85** [comment]
The walk-through only in portrait, but the enrollment process can be in landscape or portrait.
Could you show the walk-through in landscape also?
Remember the idea of Marie, to pin up the background, actually the background moves with all element.
