### ISSUE TITLE
New policy to disable or enable TLS for MQTT

### ISSUE THREAD

**Issue by btry** [flyve-mdm/android-mdm-agent#193]
Hi

I revived this branch
https://github.com/flyve-mdm/flyve-mdm-glpi-plugin/pull/40

To make this branch useful we need ability in the agent to turn on/off TLS for MQTT from a policy.

**Comment by rafaelje** [comment]
@btry I can get this policy and turn off/on TLS and reconnect please can you provide me the topic and the JSON format

**Comment by btry** [comment]
Here is the documentation. The group of policies for it is **MDM** and is repeated in the JSON message

https://github.com/flyve-mdm/flyve-mdm-glpi-plugin/wiki/MQTT-messages-specification#example-to-turn-on-or-off-tls-for-mqtt
