### ISSUE TITLE
MDM Agent as Privileged app

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-mdm-agent#197]
Hi, @rafaelje 

I got this error when I push the apk in  /system/priv-app and I restart the device.
No @thestralbot message in the group.

![image](https://user-images.githubusercontent.com/663460/33015804-5e34e28c-cdec-11e7-8d26-5e1cb2fb75f2.png)

**Comment by rafaelje** [comment]
- This issue was solved on this PR:
Ref: https://github.com/flyve-mdm/android-mdm-agent/pull/199
