### ISSUE TITLE
No log as privileged app

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-mdm-agent#198]
Hi, @rafaelje 

PING works, but no MQTT Logs.
The app is in /system/priv-app

![image](https://user-images.githubusercontent.com/663460/33016662-af0c361c-cdef-11e7-8a85-80fdff3a960b.png)

**Comment by rafaelje** [comment]
- This issue was solved on this PR:
Ref:  https://github.com/flyve-mdm/android-mdm-agent/pull/199
