### ISSUE TITLE
Possible saturation of filesystem with a .lck fle

### ISSUE THREAD

**Issue by btry** [flyve-mdm/android-mdm-agent#206]
Hi

I found this

![image](https://user-images.githubusercontent.com/14139801/33176848-cef7eb2e-d060-11e7-8251-d5bed680ed7f.png)

![image](https://user-images.githubusercontent.com/14139801/33176853-d340fb76-d060-11e7-936b-d522f74bbbcb.png)

Note from @ajsb85 : 
https://wiki.eclipse.org/Paho/Log_and_Debug_in_the_Java_client

We need to limit this to reasonable amount

**Comment by rafaelje** [comment]
I found more information about this issue, if the device has less than 200MB free, throw some exception,

This is the way that this library implements to store QO2 messages, we can change the default store path or I'll try to clear these folders with MqttDefaultFilePersistence on destroy service

https://stackoverflow.com/questions/42219041/mqttconnection-throws-exceptionfailed-to-ensure-directory-when-trying-to-conne
