### ISSUE TITLE
Download links broken on F-Droid

### ISSUE THREAD

**Issue by IzzySoft** [flyve-mdm/android-mdm-agent#209]
Your download links (F-Droid, Releases page) are broken: on F-Droid it gives a 404 error, and on the Releases page there's no `.apk`. Are you going to place the downloads on the linked locations (well, F-Droid will take a little – but the Releases page should be managable)?

**Comment by rafaelje** [comment]
Hi @IzzySoft we are not ready on F-Droid now, we are going to be there soon

**Comment by IzzySoft** [comment]
Ah, so those links are "promises not yet fulfilled" :wink: If you had the `.apk` files on the resp. `releases/` I could fill in meanwhile (you might have heard of [my F-Droid repo](https://apt.izzysoft.de/fdroid/)). Once you're in the official repo and want them removed from mine again, dropping a note (e.g. here) is all that's needed, @rafaelje .

**Comment by rafaelje** [comment]
I hope It will be ready the next week but thanks! @IzzySoft

**Comment by IzzySoft** [comment]
Fingers crossed! Anyhow, if need arises let me know. And be it for another project :wink: I'm a bit limited (no funding, and a one-man-show) – but if I can I try my best to help supporting the FOSS idea(l)s.

**Comment by ajsb85** [comment]
Hi, @IzzySoft 
Here is the task of the submission to F-Droid:
https://github.com/flyve-mdm/android-mdm-agent/issues/31

**Comment by IzzySoft** [comment]
Nothing I can do to it. You've linked the MR already there, it still has unsolved discussions (which most likely is the reason it's not processed further). Not sure what you expect me to do about it (as you've pinged me)?

**Comment by ajsb85** [comment]
I'm sorry for disturb you @IzzySoft
You can subscribe to the notifications of the MR on GitLab.
We already released a candidate for the next version 2.0
We'll notify you when it's available on F-Droid.

**Comment by IzzySoft** [comment]
Ah, OK – thanks, got you wrong (thought you sought my help in the submission process). No need to notify me, I'm meanwhile closer involved with F-Droid (part of the team), so I will notice once the app is published. Thanks a lot!

**Comment by rafaelje** [comment]
@IzzySoft the app is waiting for review https://gitlab.com/fdroid/fdroiddata/merge_requests/3542

**Comment by IzzySoft** [comment]
Great! I've just checked the unresolved discussions and, seeing they are solved, resolved them. Should be ready to go then.

**Comment by ajsb85** [comment]
Hi, @IzzySoft 
The README provide the proper URL to download the APK from F-Droid.
And the release section on GitHub provide also the artifacts.
Thank you for the issue report and thank you for the follow up on GitLab.

**Comment by IzzySoft** [comment]
Great! And: always glad to help :wink:
