### ISSUE TITLE
Implement telemetry data

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/android-mdm-agent#270]
Manage customer references and telemetry data

Review information about GLPI Telemetry
http://glpi-project.org/telemetry/

Find information about the API and Implementation, to do this we need help from @btry and @DIOHz0r 

Are we going to create a new library to implement the telemetry data?

**Comment by btry** [comment]
We already got many data about devices and agents in the backend. Why not simply implement the telemetry feature in  the backend, and not the agents ?

**Comment by rafaelje** [comment]
It's ok for me to implement on backend
