### ISSUE TITLE
Request for password until the user provide one

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/android-mdm-agent#280]
#### Observed Results:
on `Policy/passwordEnabled`

The agent launch one screen to request the password on the device for user but if the user closes it the agent does not request never to the user to do it again, IMO we need to remember the user to implement the password requested every 15 minutes to make time to the user to do it with calm

@ajsb85 what do you think?

**Comment by ajsb85** [comment]
Hi, @rafaelje 

One way is to keep alive a notification, and close it when the user already set the password

![image](https://user-images.githubusercontent.com/663460/35570852-ab8cc4ca-05d0-11e8-897a-a2c51bba2acb.png)

**Comment by rafaelje** [comment]
Fine I like that way is really annoying this message and you need close it

**Comment by rafaelje** [comment]
This is how looks like

![captura de pantalla 2018-03-20 a la s 6 10 18 p m](https://user-images.githubusercontent.com/4085091/37686018-188534f6-2c6c-11e8-8a04-3cf7b47e5e45.png)
