### ISSUE TITLE
Recurrent inventory feature

### ISSUE THREAD

**Issue by btry** [flyve-mdm/android-mdm-agent#282]
Simply refer to  the description of the feature here

https://github.com/flyve-mdm/glpi-plugin/issues/290

**Comment by rafaelje** [comment]
I review the information get ready when this policy be available

**Comment by btry** [comment]
I suggest the symbol "inventoryFrequency", if you want to begin implementation. Consider the passed value is the number of minutes, as I said earlier.

**Comment by rafaelje** [comment]
This could be the policy example:
`/2/fleet/62/Policy/inventoryFrequency`

and this the message:
`{"inventoryFrequency":"1200", "taskId":148}`

**Comment by btry** [comment]
Yes, I forgot to mention the form of the message. You got it.
