### ISSUE TITLE
Improve the description on Google Play Store and F-Droid

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/android-mdm-agent#289]
We need to improve this the actual information on the store this is a simple proposal to improve,

This is the actual text
```
Flyve MDM is an open source mobile device management software (SaaS), that enables you to secure and manage all the mobile devices of your business via a unique web-based console (MDM). 

Our app makes IT Administrators daily life much easier! It offers them a wide range of enhanced functions, to efficiently manage the entire mobile fleet of the company in just a few clicks.

This app uses the Device Administrator permission
```

This is my initial proposal:
```
Flyve MDM is an open source mobile device management software (SaaS), that enables you to secure and manage all the mobile devices of your business via a unique web-based console (MDM). 

Our app makes IT Administrators daily life much easier! It offers them a wide range of enhanced functions, to efficiently manage the entire mobile fleet of the company in just a few clicks.

With our MDM Agent you could:

•	Get a complete information about the hardware, software, operative system and others options of the device and the apps installed
•	Get the geolocalization of the device anytime and any moment
•	Make a remote wipe or Lock in loose or thief case
•	Make a global deploy of yours privates apps
•	Make a global deploy of your private documents and files
•	Force security policies for all the de devices

Additional Benefits:

•	More disponibility of your devices and support to Bring Your Own Devices (BYOD)
•	Keep secure the information of your business with the policies for all the devices

This app uses the Device Administrator permission
```

**Comment by Naylin15** [comment]
I moved the proposal to this [Hackmd](https://hackmd.io/KYM2CYE4BMBYGMC0B2AHMAzI2rpYEb6zKKSwCMkAbOQAwgiq0CsQA===) for better edition.

Here is the link to google play to see the actual in display [MDM Agent](https://play.google.com/store/apps/details?id=org.flyve.mdm.agent)

**Comment by Naylin15** [comment]
Update:

After review and improvements by @bootbeep this is the new proposal

[Hackmd](https://hackmd.io/KYM2CYE4BMBYGMC0B2AHMAzI2rpYEb6zKKSwCMkAbOQAwgiq0CsQA===?both)

**Comment by rafaelje** [comment]
This is the complete text improved, I love it and is ready on the store:

---------

Flyve MDM® is an award winning mobile device management software that enables organizations manage their entire mobile fleet with ease. Give your IT security team a broader visibility to proactively work on security weaknesses and manage risk on Apple® iOS and Google Android™ mobile devices.

**Control It!**
Flyve MDM® offers a range of powerful security features in an intuitive web interface that allows you to monitor unauthorized behavior and prevent damage of your organization’s employees, image, brand and public reputation.

**Powerful Features**
•	Ability to control and configure every device.
•	Remotely erase all content and settings on your device.
•	Remotely lock terminals.
•	Activate remotely encryption.
•	Real-time geolocation.
•	Bluetooth® and Wi-Fi connectivity control.
•	Control camera both front and facing.
•	Install and uninstall applications remotely.
•	Set the level of complexity of your passwords.
•   Support to Bring Your Own Devices (BYOD).

**A Safe Context for Employees**
Make employees comply safety standards in your network, Flyve MDM® make it easier for the IT team to oversee and control security levels of every device remotely without any employee time and effort, it just works.

**Reduce Leaks**
Flyve MDM® helps you reduce the risk of sensitive corporate data leaks and loss of intellectual property. In case of stolen or lost devices, you can disable and wipe information with just one click.

_Take the proactive approach._

Try it Now.

This app uses the Device Administrator permission

-------------
