### ISSUE TITLE
MQTT best practices

### ISSUE THREAD

**Issue by btry** [flyve-mdm/android-mdm-agent#291]
see https://github.com/flyve-mdm/glpi-plugin/issues/313

We need to drop the leading slash in MQTT topics of agents and fleets

**Comment by rafaelje** [comment]
The agent is ready for this change, let's do it

**Comment by btry** [comment]
OK,

I'll try to create a PR to clean completely the persisted MQTT messages and rebuild them. We have several changes requiring this, this issue too.
