### ISSUE TITLE
Policy is apply on the Agent Feedback

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/android-mdm-agent#299]
The plugin MDM has the ability to get the response if the policy is apply or not in the Agent

Needs more information from @btry to know how to implement this characteristic on the agent

**Comment by btry** [comment]
Documentation updated in the mqtt messages specification

**Comment by rafaelje** [comment]
I think this is the documentation:

http://flyve.org/glpi-plugin/development/specifications/#task-status

**Comment by btry** [comment]
yes !
