### ISSUE TITLE
Error message still present after successfully enrolled

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-mdm-agent#3]
### Expected behaviour
Remove error message after successfully enrolled.

### Actual behaviour
The message `The serial already exists` still present.

### Environment Details

- Android Version: 5.1
- Device: Xiaomi Redmi 3
- App Version: 0.99.42

### Steps to reproduce the behaviour

1. Send an invitation
1. Enroll the device
1. Clear cache of the android app 
1. Send an invitation
1. Enroll the device
1. The error of the serial appear
1. Go to the admin console
1. Remove the device
1. Click next in the android app
1. Successfully enrolled

### Screenshots

![image](https://cloud.githubusercontent.com/assets/663460/21420923/9a4b346e-c830-11e6-9e7a-bbef87e6382b.png)

**Comment by ajsb85** [comment]
We are rewriting the app.

**Comment by rafaelje** [comment]
This problem occurs because when removing the device from the dashboard the serial is still kept in the database, we must validate it with @btry

**Comment by ajsb85** [comment]
Hi, @rafaelje 
This issue still persist?
Take a look to close or to review in deep with @btry 
Thanks.

**Comment by btry** [comment]
Hi

The issue will persist. This is a check in the Flyve MDM backend. 

When an agent is deleted, the associated computer is deleted too. This problem should happen only when playing too much with the database (uninstal / reinstall of the plugin may lead to this issue for example).

Maybe could we improve a bit more the enrollment process. 
* before the enrollemnt the agent starts an inventory
* in the enrollment payload, we add the inventory XML
* we use the XML to run  the import rules implmented in FusionInventory
* we get the ID of the created OR updated computer
* we use this ID to associate a computer to the agent in Flyve MDM backend

Several things to consider in this scenario:
- FusionIvnentory may deny the import => this will lead to an enrollment failure (enrollment denied by inventory settings)
- I'm not sure yet we can run ourselve the import rules and get the ID of the computer found / created.
