### ISSUE TITLE
GPG App Usage

### ISSUE THREAD

**Issue by jarrodldavis** [flyve-mdm/android-mdm-agent#305]
Hi there,

I noticed that you are using my [GPG GitHub App] to make sure pull request commits are signed with valid GPG signatures.

Unfortunately, I've stopped working on this app quite some time ago because I had issues getting correct information from the GitHub API. You may have noticed some false negatives, especially when pushing new commits to an existing pull request.

Additionally, it seems GitHub has recently added a "Require signed commits" option for branch protection, as seen below:

<img width="761" alt="screen shot 2018-03-18 at 12 15 07 pm" src="https://user-images.githubusercontent.com/235875/37568652-35b8be84-2aa6-11e8-949c-e585eb8d4164.png">

While I don't plan on taking down the hosted version of the GitHub App any time soon, I would strongly recommend either using this new built-in option or forking and hosting your own version of the app (with your own fixes and improvements) since I don't plan on updating it.

[GPG GitHub App]: https://github.com/jarrodldavis/probot-gpg

**Comment by ajsb85** [comment]
Answered here:
https://github.com/flyve-mdm/web-mdm-dashboard/issues/492
