### ISSUE TITLE
Submit Application to F-Droid

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-mdm-agent#31]
### Template to discuss the inclusion on F-Droid

* [x] The app complies with the [inclusion citeria](https://f-droid.org/wiki/page/Inclusion_Policy)
* [x] The app is not already listed in the repo or issue tracker.
* [x] The original app author has been notified (and supports the inclusion).

---------------------

### Link to the source code: 

https://github.com/flyve-mdm/flyve-mdm-android

### Link to app in another app store: 

https://play.google.com/store/apps/details?id=com.teclib.flyvemdm

### License used: 

GPLv3

### Description: 

Flyve MDM is an open source mobile device management software (SaaS), that enables you to secure and manage all the mobile devices of your business via a unique web-based console (MDM). 
Our app makes IT Administrators daily life much easier! It offers them a wide range of enhanced functions, to efficiently manage the entire mobile fleet of the company in just a few clicks.

---
Related links:
- https://f-droid.org/contribute/
- https://forum.f-droid.org/
- https://f-droid.org/forums/forum/submission-queue/
- https://f-droid.org/wiki/page/Inclusion_Policy
- https://f-droid.org/manual/

**Comment by ajsb85** [comment]
A complete template:

http://hackmd.teclib.infra/s/H1HZpLwCg

**Comment by ajsb85** [comment]
Hi, @Naylin15  
It's a task to-do for you. 
Fill the content and descriptions to submit to F-Droid.
The template is already on HackMD
Thanks.

**Comment by ajsb85** [comment]
Hi, @rafaelje 

Please, provide here the URL of the Merge Request in F-Droid when it's ready.

Thanks.

**Comment by Naylin15** [comment]
Hi,

In this issue is the description for F-Droid #289

**Comment by ajsb85** [comment]
Hi, @flyve-mdm/mobile-development 
Waiting for this MR on GitLab
https://gitlab.com/fdroid/fdroiddata/merge_requests/3542

**Comment by rafaelje** [comment]
The app is waiting for merge on F-Droid with RC.4 I'll close this issue and continue with this process here:
https://github.com/flyve-mdm/android-mdm-agent/issues/209
