### ISSUE TITLE
Deploy app workflow

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-mdm-agent#32]
Hi, @rafaelje 

Based on F-Droid install app notifications

![image](https://cloud.githubusercontent.com/assets/663460/25616531/a3e187c0-2f3d-11e7-8318-c8ffaf0a8dbd.png)

![image](https://cloud.githubusercontent.com/assets/663460/25616665/6e591a0e-2f3e-11e7-8a7f-6f14a77dd588.png)

**Comment by ajsb85** [comment]
F-Droid source code https://gitlab.com/fdroid/fdroidclient

/cc @rafaelje

**Comment by ajsb85** [comment]
Hi, @rafaelje 

The idea  of this task is to show to the user the progress of the download of the apps.
Could you take a look in the source code of F-Droid client to reuse the code?
To going faster 💪 

Thanks.

**Comment by rafaelje** [comment]
This feature is already implemented
