### ISSUE TITLE
MQTT SSLHandshakeException 

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/android-mdm-agent#328]
When I try to connect to the MQTT I got this error message:

```
MqttException (0) - javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

**The strange thing is that the first time that you connect when enrolling the device everything working fine but if you disconnect for any reason and try to connect again throw the SSL Exception**

If I connect with MQTTBox and the same credentials of the agent works fine, This is a new issue I try with the old version of the app and keep the same

This error begins when the certified expired

**Comment by btry** [comment]
```Trust anchor for certification path not found```

I'll check with OpenSSL the certification chain. Maybe I misconfigured the server when updating the certificates, but testssl tool did not revealed anything worrying though.

**Comment by rafaelje** [comment]
@btry found the issue on the servers was some problem with the Cert
