### ISSUE TITLE
deeplink not processed correctly

### ISSUE THREAD

**Issue by btry** [flyve-mdm/android-mdm-agent#329]
The agent does not processes the deeplink correctly when it receives 

on the device I get tne message "Problems with deep link"

While debugging the app I see the following

![image](https://user-images.githubusercontent.com/14139801/38130894-11bb5768-3405-11e8-9f05-cf9e1cedd1b1.png)

the deeplink must be splitted to get only the value of data in the query string.

This may be related to the issue I fixed yesterday with the QR code, where the leading part of the URL it contains was missing.

**Comment by btry** [comment]
False alert.

**Comment by betweenbrain** [comment]
I am currently experiencing this issue with v2.0.0-rc.4.2518 of the agent. Is there a fix for this as this issue was closed?

**Comment by rafaelje** [comment]
Hello @betweenbrain!

Are you working with your own environment or with some of our demo site like https://demo-dashboard.flyve.org/?

If you are working with you own environment you can check the deeplink you will have and string like this:

```
http://flyve.org/deeplink/?data=aHR0cHM6Ly9kZW1vLWFwaS5mbHl2ZS5vcmcvYXBzdC5waHBcO25sSlp3T1gyVzZZbG5jdWxvcDVQaGc1WHpoV0l0ZnNKSVh3Vjd2S1pcOzVhMDlkMGJjMTY3YzY3NDVmNzdkOWYzNTM5MmJhZmIxNjVmMGNkMTlhZGY4NjBlYzdhOWIxOTQ5YWNkOTEytcOw==
```

extract the base64 encode before "data="

and you will get a CVS format

with the url, user token, invitation token, name, phone, etc... if you get something different will get problems with deeplink

**Comment by betweenbrain** [comment]
Hi @rafaelje, thanks for the quick response. I am working with the environment at https://demo.flyve.org. Is this not the correct one to use?

**Comment by rafaelje** [comment]
Yes, is correct you can work with it, which Android version did you try? could you share here the deeplink url or the QR that you are trying

**Comment by betweenbrain** [comment]
Great, thanks for confirming. The QR code is
![5bad1368c343c](https://user-images.githubusercontent.com/634119/46176058-18a50000-c27c-11e8-91d0-71dc09206572.png)

**Comment by betweenbrain** [comment]
Sorry, I forgot to add that this is with Android v6.0.1

**Comment by rafaelje** [comment]
Hello @betweenbrain!

You are right, your QR is empty because this site https://demo.flyve.org is going to be deprecated  very soon, instead Please review these sites:

GLPI with Flyve Plugin
https://demo-api.flyve.org/front/central.php

or our new web Dashboard
https://demo-dashboard.flyve.org/

with the default credentials:
User: glpi
Password: glpi

**Comment by betweenbrain** [comment]
Thanks, that did the trick!

**Comment by egeu5** [comment]
I could not login on demo-api or demo-dashboard with those credentials. I want to test the software but I couldnt even log me in...

**Comment by ajsb85** [comment]
Hi, @egeu5 
Write an email to contact@teclib.com to request the credentials.

Here the instructions:
https://flyvemdm-doc.readthedocs.io/en/latest/partners/demo.html

**Comment by egeu5** [comment]
Thanks!
Probably you should put the "old" demo dashboard offline. I was a little bit confused about the different applications.
