### ISSUE TITLE
Enrollment requires an inventory at enrollment

### ISSUE THREAD

**Issue by btry** [flyve-mdm/android-mdm-agent#330]
The backend expects an inventory XML being sent whern a device enrolls. 

It seems this is not the case: enrollment fails with "Device inventory XML is mandatory".

**Comment by rafaelje** [comment]
The agent is sending the inventory correctly

**Comment by olrao** [comment]
I tried to enroll through the android agent. I got the same error. `Device inventory XML is mandatory.`

Please let me know if you need more details
I am using MDM Agent version 3.0.0

**Comment by btry** [comment]
Hi @olrao 

Please install this version: https://play.google.com/apps/testing/org.flyve.mdm.agent

**Comment by olrao** [comment]
Thanks. I have successfully enrolled from the app. I can see my device listed in the Dashboard. But the Dashboard shows that the device is **OFFLINE**, even though its **ONLINE**.
Also when i tried to ping the device, the Dashboard says it is **BAD REQUEST**. But when i open the app to check the Activity logs, I can see that there has been a **PING** query request.

Somehow it seems to be one way comms.

What am i missing here.
Thanks for your support.

**Comment by btry** [comment]
Hi

To help you in such issue It would be easier to discuss in live. Can you join us on telegram ( https://t.me/flyvemdm ) or on IRC ( freenode #flyve-mdm ) ?

**Comment by btry** [comment]
I identified a bug yesterday evening about ping, and the fix is merged. I restarted the mqtt client daemon which may need a restart to take into account the fix. 

Can you try ?
