### ISSUE TITLE
VPN Settings

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-mdm-agent#34]
Hi, @rafaelje 

It's purpose is to start, stop and monitor the state of VPN tunnels in a style very similar to the WiFi Settings app that comes with android.

https://f-droid.org/repository/browse/?fdfilter=VPN

**Comment by rafaelje** [comment]
This is a very interesting issue I was looking information about this issue and we need to understand well what we need here:

- Create a new VPN, any specification in particular ipsec, openvpn, l2tp, I need be clear about what is the VPN that we can create with Android.

With the search on F-Droid just get two projects with the same kind of VPN I'll check in deep what they do it

**Comment by rafaelje** [comment]
how to disconnect a VPN connection:

available on API 21

```
        ConnectivityManager cm = (ConnectivityManager)context.getSystemService(Context.CONNECTIVITY_SERVICE);
        Network[] networks = cm.getAllNetworks();

        for(int i = 0; i < networks.length; i++) {

            NetworkCapabilities caps = cm.getNetworkCapabilities(networks[i]);

            Log.i("", "Network " + i + ": " + networks[i].toString());
            Log.i("", "VPN transport is: " + caps.hasTransport(NetworkCapabilities.TRANSPORT_VPN));
            Log.i("", "NOT_VPN capability is: " + caps.hasCapability(NetworkCapabilities.NET_CAPABILITY_NOT_VPN));

        }
```
