### ISSUE TITLE
Issues downloading files

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-mdm-agent#342]
#### Observed Results

![image](https://user-images.githubusercontent.com/663460/38443586-7d317648-39ec-11e8-9d80-a8bc906f86f1.png)

**Comment by ajsb85** [comment]
![image](https://user-images.githubusercontent.com/663460/38444236-d6dae948-39ee-11e8-82c3-0f80474bc747.png)
![image](https://user-images.githubusercontent.com/663460/38444241-d9857046-39ee-11e8-9e59-f126f6c29a10.png)

**Comment by rafaelje** [comment]
With the first attempt trying to reproduce this error on a simulator, I can download the file correctly I'll try again in a real device on emulator the files was on /storage/emulator/0/Documents

**Comment by rafaelje** [comment]
I cannot reproduce the error on 2 devices runs great, @ajsb85 please check if the file is stored in internal storage -> /sdcard/Documents

![e25e248c-543d-4f57-925b-e8cfcafecfc8](https://user-images.githubusercontent.com/4085091/38521720-85276130-3c14-11e8-867d-9108119d9807.jpeg)

![64111ad0-181a-43d7-90e7-450266e77aa2](https://user-images.githubusercontent.com/4085091/38521721-86292a3c-3c14-11e8-950f-1bd3c5ca0622.jpeg)

**Comment by rafaelje** [comment]
I want to create a new space like the application to view the files deployed

**Comment by ajsb85** [comment]
Hi, @rafaelje 
Could you add some tests and logs to debug in my device and collect the information?

**Comment by rafaelje** [comment]
@ajsb85 yes now with the new versión you can see the complete path of the file on the new screen file on menu -> activity -> files, also are improved the message is anything is wrong please let me know if you still got some problem

**Comment by rafaelje** [comment]
I need to review the download progress bar and check if is open with a persistence option

**Comment by rafaelje** [comment]
![ezgif-1-b5f139cf93](https://user-images.githubusercontent.com/4085091/39371625-3d85e5b8-4a10-11e8-8347-df2c58ff2eb5.gif)
