### ISSUE TITLE
Missing kill Session between 2 attempts to enroll

### ISSUE THREAD

**Issue by btry** [flyve-mdm/android-mdm-agent#349]
## steps to reproduce

- I try to enroll the device with the agent and the invited user is A
- the enrollment fails (no matter the reason)
- I try to enroll again the device, the invited user is B

I observe the MDM agent tries to use again the session of the user A

## solution

The MDM agent must kill its session after the enrollment completes OR fails.

**Comment by rafaelje** [comment]
When the enrollment start now is deleting all the MQTT information
