### ISSUE TITLE
Problem with the APK certification

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/android-mdm-agent#384]
#### Observed Results:

With the new version of Gradle cannot certified the APK

got this error:
```
Expected a name but was STRING at line 1 column 99 path $[0].apkInfo.versionName
```

**Comment by rafaelje** [comment]
With the new gradle version you need select a different folder to store the APK

**Comment by manuel179** [comment]
Appname = Servidor MTP
Package name = com.android.mtp
Version = 7.1.2
Code version = 25

Appname = SIM Telcel
Package name = com.android.stk
Version = 2.0
Code version = 25
