### ISSUE TITLE
Invalid User Token

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-mdm-agent#409]
Invalid user token
Bug reported by Bezons in Telegram
Reference:
https://t.me/flyvemdm/1790

![image](https://user-images.githubusercontent.com/663460/39587414-bf1d67e8-4ef9-11e8-91a4-b812c7d686e3.png)

**Comment by rafaelje** [comment]
Needs to create a new invitation the user token maybe was expired

**Comment by ajsb85** [comment]
Needs a workflow to know what he can do after that.

**Comment by rafaelje** [comment]
This is the workflow:

- Close the MDM Agent
- Go to the Web Dashboard or GLPI Plugin 
- Create a new invitation
- Open the deeplink to enroll again from the device
- Start the enrollment process again
