### ISSUE TITLE
String cannot be converted to JSON object

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-mdm-agent#410]
String cannot be converted to JSON object in the request permission screen.
Reported by Bezons in Telegram

Reference:
https://t.me/flyvemdm/1722

![image](https://user-images.githubusercontent.com/663460/39587471-d85989bc-4ef9-11e8-87c2-f330d60714a8.png)

**Comment by rafaelje** [comment]
This error generally appears when the user doesn't have permission to enroll, however, the message is more clear now, this permission error comes from the Flyve plugin
