### ISSUE TITLE
Enhance messages

### ISSUE THREAD

**Issue by btry** [flyve-mdm/android-mdm-agent#413]
In enrollment process we may have error messages from the REST API

![image](https://user-images.githubusercontent.com/14139801/39618568-9cd497de-4f84-11e8-9210-ab95b174a6d6.png)

Unfortunately, the enrollment process issues several requests, and the error message the agent may receive appears out of context, making harder to understand what happened.

We should consider prepend the message returned by the API with an extra string. For example "Failed to login: " followed by the original message.

**Comment by rafaelje** [comment]
All the generics messages were deleted and add complete information about the version enrollment process
