### ISSUE TITLE
Disable USB conection

### ISSUE THREAD

**Issue by DIOHz0r** [flyve-mdm/android-mdm-agent#414]
**Describe the bug**
When you apply "Disable USB PTP", "Disable USB PTP" and "Disable USB ADB" at the same time the device is not recognized when it's connected however if you device is connected and click on the notification from the status bar and tab on any option for USB the policies doesn't work and let you work with the device files.

**Comment by rafaelje** [comment]
This is because I cannot find any broadcast with the message of this change

**Comment by rafaelje** [comment]
I'm working with this broadcast ACTION_USB_DEVICE_ATTACHED

https://stackoverflow.com/questions/39942453/how-to-receive-usb-connection-status-broadcast
