### ISSUE TITLE
Limit the quantity of notifications

### ISSUE THREAD

**Issue by btry** [flyve-mdm/android-mdm-agent#434]
The MDM agent tries regularly to download a resource. If it fails a lot of times, we have a facebook wall

![image](https://user-images.githubusercontent.com/14139801/39933879-6e8cdcf4-5544-11e8-813f-860e8c81fe7b.png)

by the way, some notifications don't have a small icon on the right (see the topmost one in  the screenshot)

**Comment by MONIKA-KUMAR-JETHANI** [comment]
Hi @btry , Is this fixed?

**Comment by btry** [comment]
Hi, not yet fixed. Please be patient.

**Comment by MONIKA-KUMAR-JETHANI** [comment]
@btry I would like to work on this.

**Comment by btry** [comment]
still true 

![image](https://user-images.githubusercontent.com/14139801/44212110-c6e06480-a16a-11e8-80b5-23b509dee86f.png)

**Comment by ajsb85** [comment]
Hi, @rafaelje 
Please, use the same Android version in the device of @btry

**Comment by btry** [comment]
The issue occurs when the device is in real life. Instead of open and close the agent, enable and disable the WiFi several times.

**Comment by rafaelje** [comment]
To make the agent more silently I'm going to remove the progress notification download
