### ISSUE TITLE
Display issue in carousel in landscape mode

### ISSUE THREAD

**Issue by btry** [flyve-mdm/android-mdm-agent#468]
In landscape mode the 3 dots showing our position in the carousel conflict with the text. i'll add a screenshot in a few hours

**Comment by rafaelje** [comment]
![be1f4c9c-4434-4ee5-a070-dd68de519d6f](https://user-images.githubusercontent.com/4085091/41046300-30c25230-6978-11e8-9736-5eea4c42b8f3.jpeg)

**Comment by rafaelje** [comment]
<img width="695" alt="captura de pantalla 2018-06-27 a la s 5 11 37 p m" src="https://user-images.githubusercontent.com/4085091/41999966-3e4ab512-7a2d-11e8-8b9b-c841e94fa93c.png">

Creating a new layout exclusive for landscape
