### ISSUE TITLE
Loop creating a new release with CI

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/android-mdm-agent#470]
@Naylin15 review the CI process actually has a loop when creating a release

**Comment by Naylin15** [comment]
Right away 👍 

Thank you

**Comment by Naylin15** [comment]
This is solved on the following [script](https://github.com/Naylin15/android-mdm-agent-fork/blob/feature/ci/ci/scripts/ci_validate_workflow.sh)

Now the new commit will be validated to prevent the loop

**Comment by Naylin15** [comment]
This issue is solved, we can close it
