### ISSUE TITLE
MAC Address detection 

### ISSUE THREAD

**Issue by MsTsankur** [flyve-mdm/android-mdm-agent#472]
Hi guys.

I'm currently working with Zebra's PDA (TC56, TC25) and in the inventory generated do not contain the right MAC address.

"<DEVICEID>18072521400629_02:00:00:00:00:00</DEVICEID>"

At enrollment my device overwrite the previous fusion agent with the new device. I have the "Computer update (by mac) rule enabled and I CANNOT disable it.

**Comment by rafaelje** [comment]
This issues is solved with the new version, we upgrade the Inventory library to fix this issue:

Ref: https://github.com/flyve-mdm/android-mdm-agent/pull/480
