### ISSUE TITLE
Error forming user information with foreing letters

### ISSUE THREAD

**Issue by Ebesan** [flyve-mdm/android-mdm-agent#474]
**Describe the bug**
In the device enrollment phase where I form my User information it won't accept "ä" or "ö" or "å" letters.

**To Reproduce**
1. Invite new device to Flyve MDM
2. Enroll the new device via email
3. In the Enrollment phase in Flyve mdm mobile app fill one of the user information fields with ä, ö or å
4. Try to accept the enrollment and see the error

**Expected behavior**
You should able to do the enrollment with these letters.

**Screenshots**
![screenshot_20180612-120759](https://user-images.githubusercontent.com/40197190/41281183-7543df9e-6e39-11e8-8b0d-808f3e8468d1.png)

**Smartphone (please complete the following information):**
 - Device: Honor 7 Lite
 - OS: Android 7.0
 - Emui version 5.0.2

Additional info:
It gives JSON payload error.

**Comment by rafaelje** [comment]
<img width="451" alt="captura de pantalla 2018-06-27 a la s 4 27 58 p m" src="https://user-images.githubusercontent.com/4085091/41997826-1b8b7666-7a27-11e8-85cd-7bd53fd8c154.png">

This issue is solved
