### ISSUE TITLE
Application skips the "Permissions" page

### ISSUE THREAD

**Issue by aaursand** [flyve-mdm/android-mdm-agent#478]
Application skips the "Permissions"-page of the enrollment setup. 

**Describe the bug**
When trying to enroll a new device, I somehow skip the permissions view and end up in the user registration view of the app. This gives me an error when submitting the registration as "XML directory is mandatory". I have tried both the application-version from Google Play and installed the latest release build from here on github. 
 
**To Reproduce**
Steps to reproduce the behaviour :
1. Scan the QR-code 
2. Open the link in the Flyve MDM Agent application 
3. The Enroll device screen is shown, and I click to continue the setup-process. 
4. The app immediately jumps to the "register user" page. 
5. I fill in the required form
6. The whole prosess crashes with the "XML inventory is mandatory" error. 

**Desktop:**
 - OS: OSX High Sierra v 10.13.4
 - Browser: Safari
 - Browser version: 11.1

**Smartphones tested :**
 - Device: Samsung GT-S7710 | Samsung SM-G390F
 - OS: Android 4.1.2 | Android 7.0 
 - Browser Stock browser | Google Chrome 

**Additional context**

*More info about the setup I use:* 
The GLPi setup I use does not have access to an outgoing email-server, so I end up having to do a rather hacky solution to retrieve the deeplink from the QR-code. This is done by rebuilding the project after adding the PNG-file of the QR-code to the GLPi directory. I am not sure if this would be the cause for the issue, but I have registered that both the application and the web-dashboard application does communicate with the GLPi-server, since I can enable and disable debug-mode for apps in the Flyve MDM Demo settings.

**Comment by aaursand** [comment]
I have figured out a solution. Seems that the "release"-versions on both Github and the play store are outdated and no longer works with the flyve backend. These were the versions I installed. Would suggest to add information about this on their respective sites:

[Release on github](https://github.com/flyve-mdm/android-mdm-agent/releases)
[Release on Google play store](https://play.google.com/store/apps/details?id=org.flyve.mdm.agent)

**Comment by rafaelje** [comment]
@aaursand could confirm if you still got this problem?

**Comment by aaursand** [comment]
Hi

I found a solution. It seems that I was installing the old release versions of the android app (0.99, that is labeled release here on github). Downloading the dev version via git solved the problem. 

Some bells went off when I looked through the source code for the 0.99 version and didn't actually see any code for the permission pages.
