### ISSUE TITLE
Add Android version in compatibiliy matrix of README.md

### ISSUE THREAD

**Issue by btry** [flyve-mdm/android-mdm-agent#494]
Hi, @flyve-mdm/mobile-development 
Users ask the minimum version supported. This would be good to add the inforamtion in  the readme.

**Comment by rafaelje** [comment]
The minimum version is API 16 Android 4.1 and the maximum version tested is 25 Android 7.1.1

@Naylin15 this is my proposal:

| API | Android | Support | SSL
| --- | --- | --- | --- |
| 16 | Android 4.1 | X | - |
| 17 | Android 4.2 | X | - |
| 18 | Android 4.3 | X | - |
| 19 | Android 4.4 | X | - |
| 20 | Android 4.4 | X | - |
| 21 | Android 5.0 | X | X |
| 22 | Android 5.1 | X | X |
| 23 | Android 6.0 | X | X |
| 24 | Android 7.0 | X | X |
| 25 | Android 7.1.1 | X | X |
| 26 | Android 8.0 | - | - |

**Comment by btry** [comment]
OK for me.
