### ISSUE TITLE
Cannot enroll device

### ISSUE THREAD

**Issue by grego1981** [flyve-mdm/android-mdm-agent#500]
**Describe the bug**
When enrolling the device I get the error enrollment failed with the dismiss button, php-errors.log fills up really fast (200mb per failure!) Judging from the logs, I can only assume that because the language used on the phone is not using the latin alphabet, all these errors appear.
[php-errors.zip](https://github.com/flyve-mdm/android-mdm-agent/files/2184441/php-errors.zip)

*Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7 Edge
 - OS: Android Oreo
 - Browser Chrome
 - MDMAgent app 2.0.1-beta.1992

**Comment by rafaelje** [comment]
Hello @grego1981 the agent is not compatible with Android Oreo at this moment, you can try with Android 7.1 or below

**Comment by grego1981** [comment]
Just tried it with an android 6.0 moto xt1524, exactly the same problem... 


  *** PHP Warning(2): simplexml_load_string(): Entity: line 2: parser error : PCDATA invalid Char value 8
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string():

ÒS�ÕSUO�
     ÔÓÑ�ÐT�ÓÑ�Ð�SQO�
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string():                                                                                ^
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): Entity: line 2: parser error : PCDATA invalid Char value 16
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): �ÕSUO�
                                                  ÔÓÑ�ÐT�ÓÑ�Ð�SQOVÐÑ
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string():                                                                                ^
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): Entity: line 2: parser error : PCDATA invalid Char value 16
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): ÕSUO�
                                                 ÔÓÑ�ÐT�ÓÑ�Ð�SQOVÐÑU
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string():                                                                                ^
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): Entity: line 2: parser error : PCDATA invalid Char value 27
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): UO�
                                               ÔÓÑ�ÐT�ÓÑ�Ð�SQOVÐÑUVÓ[Ý
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string():                                                                                ^
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): Entity: line 2: parser error : PCDATA invalid Char value 11
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string():
                                              ÔÓÑ�ÐT�ÓÑ�Ð�SQOVÐÑUVÓ[Ý▒WO�
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string():                                                                                ^
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): Entity: line 2: parser error : PCDATA invalid Char value 8
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): �ÐT�ÓÑ�Ð�SQOVÐÑUVÓ[Ý▒WO�
                                                                       Ó�SQO�
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string():                                                                                ^
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): Entity: line 2: parser error : PCDATA invalid Char value 8
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): ÐT�ÓÑ�Ð�SQOVÐÑUVÓ[Ý▒WO�
                                                                      Ó�SQO�
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string():                                                                                ^
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): Entity: line 2: parser error : PCDATA invalid Char value 8
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): ÐT�ÓÑ�Ð�SQOVÐÑUVÓ[Ý▒WO�
                                                                      Ó�SQO�
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string():                                                                                ^
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): Entity: line 2: parser error : PCDATA invalid Char value 8
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): �T�ÓÑ�Ð�SQOVÐÑUVÓ[Ý▒WO�
                                                                      Ó�SQO�
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string():                                                                                ^
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): Entity: line 2: parser error : PCDATA invalid Char value 8
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): T�ÓÑ�Ð�SQOVÐÑUVÓ[Ý▒WO�
                                                                     Ó�SQO�
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string():                                                                                ^
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): Entity: line 2: parser error : PCDATA invalid Char value 15
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): �ÓÑ�Ð�SQOVÐÑUVÓ[Ý▒WO�
                                                                    Ó�SQO�
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string():                                                                                ^
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): Entity: line 2: parser error : PCDATA invalid Char value 16
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string(): �ÓÑ�Ð�SQOVÐÑUVÓ[Ý▒WO�
                                                                    Ó�SQO�
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()
2018-07-16 14:25:01 [175@itsrv-05]
  *** PHP Warning(2): simplexml_load_string():                                                                                ^
  Backtrace :
  :
  plugins/flyvemdm/inc/common.class.php:184          simplexml_load_string()
  plugins/flyvemdm/inc/agent.class.php:1129          PluginFlyvemdmCommon::parseXML()
  plugins/flyvemdm/inc/agent.class.php:451           PluginFlyvemdmAgent->enrollByInvitationToken()
  inc/commondbtm.class.php:891                       PluginFlyvemdmAgent->prepareInputForAdd()
  inc/api.class.php:1609                             CommonDBTM->add()
  inc/apirest.class.php:259                          API->createItems()
  apirest.php:46                                     APIRest->call()


Propably a character issue, I use greek language on the phone.

**Comment by grego1981** [comment]
I just changed the language to US English and it enrolled as it should.

**Comment by rafaelje** [comment]
Thanks for your advice @grego1981  I'll test with greek to reproduce the problem
