### ISSUE TITLE
Tests failed on CircleCI

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-mdm-agent#508]
Hi, @rafaelje 

**ci/circleci: test_api_v16** — Your tests failed on CircleCI

https://circleci.com/gh/flyve-mdm/android-mdm-agent/2066?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by rafaelje** [comment]
The test will start to fail because CircleCI remove the emulator support some days ago https://github.com/circleci/circleci-images/issues/140 in some case works and other don't work but now the deploy is complete we need move to Firebase test for this

**Comment by rafaelje** [comment]
Here is the official documentation with the information:
https://circleci.com/docs/2.0/language-android/#overview

> Running the Android emulator is not currently supported by the type of virtualization CircleCI 2.0 uses on Linux. To run emulator tests from a job, consider using an external service like Firebase Test Lab. To do this, you can use the gcloud command line. Google Cloud tools are preinstalled in our Android Docker images, which you can find on GitHub or Docker Hub.

**Comment by rafaelje** [comment]
This project share information about Firebase Test Lab and how to implement it to get Code Coverage with JaCoCo this is one of the problems that we have without an emulator

https://medium.com/@ayltai/all-you-need-to-know-about-circleci-2-0-with-firebase-test-lab-2a66785ff3c2

https://github.com/ayltai/Newspaper

**Comment by rafaelje** [comment]
The instrumentation test done! 👍
