### ISSUE TITLE
Erase logs on enrollment

### ISSUE THREAD

**Issue by btry** [flyve-mdm/android-mdm-agent#537]
Hi

I noticed that if I enroll a device which was previously enrolled, I find MQTT logs from previous enrollments.

I think we should drop those logs before attempting to connect with MTT for the first time.

Also we may need to limit the size of the logs.

**Comment by rafaelje** [comment]
Got it

**Comment by rafaelje** [comment]
This is the actual behavior:

- enroll the device the first time and save the data
- if try to add a new enrollment with deeplink you cannot do it will open the main screen without saving any data
- if you get an unenroll command delete all the information

But I need a way to remove the information if the device is without connection, and here the one time password will be amazing

**Comment by btry** [comment]
Hi
Actually I was not silly enough to try to enroll after being already enrolled. Good point. 

However the topic of this issue was i noticed that mqtt logs device side seems to not ber cleared upon enrollment (at date of writing the issue). I'll try to re-enroll with the latest version of the agent and validate the reset soon.
