### ISSUE TITLE
Parameter user_token seems invalid

### ISSUE THREAD

**Issue by spinaldf** [flyve-mdm/android-mdm-agent#549]
Hi, I have this problem with app Flyve MDM Agent, I don't have idea what is problem, what to do?

My  following steps: 

This part, Create invetory and try create session, when show this error.

![screenshot_2018-08-22-13-44-57](https://user-images.githubusercontent.com/42477982/44477706-c552e880-a611-11e8-82b7-d553835ee7ce.png)

Details of my Config.

![1](https://user-images.githubusercontent.com/42477982/44477765-fc28fe80-a611-11e8-9af0-e156d9219034.png)
![2](https://user-images.githubusercontent.com/42477982/44478327-b9682600-a613-11e8-9162-373be73d43d2.png)

I use Ldap authentication and Work on GLPI.

**Comment by rafaelje** [comment]
@spinaldf please review the deep link is a string with this format:

```
http://flyve.org/deeplink/?data=WIxOTk2NmRiNDQ0ZmE3OGY0MDkyOGI0ZDNmMGRkY2Q4MjM4MDBkYjM5YTUzOFw7R3JlYXQgc3VwcG9ydFw7KzMzIDEyMzQ1Njc4OVw7aHR0cHM6Ly9teWdyZWF0c3VwcG9ydC5jb21cO2dyZWF0c3VwcG9ydEBleGFtcGxlLmNvbQ==
```

Please review this section: `WIxOTk2NmRiNDQ0ZmE3OGY0MDkyOGI0ZDNmMGRkY2Q4MjM4MDBkYjM5YTUzOFw7R3JlYXQgc3VwcG9ydFw7KzMzIDEyMzQ1Njc4OVw7aHR0cHM6Ly9teWdyZWF0c3VwcG9ydC5jb21cO2dyZWF0c3VwcG9ydEBleGFtcGxlLmNvbQ==`

This is a base64 encode you can decode with some online service like https://www.base64decode.org/ or add the string here to help you, there you will find a cvs format and you can see if the user_token is present the user_token has a format like this `Abadsfdfsdf344dfgdgdfg`

**Comment by spinaldf** [comment]
Ready, This error can't show more. I remove all configuration API and insert datas again.

Look My new configuration.

![a1](https://user-images.githubusercontent.com/42477982/44525477-69429f80-a6b7-11e8-8702-fec27e454dc3.png)
![a2](https://user-images.githubusercontent.com/42477982/44525478-69429f80-a6b7-11e8-9f71-0ad7f73e395c.png)

**Comment by rafaelje** [comment]
can I close this issue @spinaldf?

**Comment by spinaldf** [comment]
yes.

**Comment by rafaelje** [comment]
Thanks you!
