### ISSUE TITLE
Android Agent - MDMAgent.java isSecureVersion() - ?

### ISSUE THREAD

**Issue by jdavidthomson** [flyve-mdm/android-mdm-agent#550]
**Describe the bug**
Enrollment works fine.  When I go to the glpi plugin to lock a device nothing happens unless I change the constant in this method to false, rebuild and redeploy the apk to my device.  After that, all major functions I've tried are working - except for inventory.

**To Reproduce**
1. Setup Docker Environment
2. Checkout latest RC branch of Agent
3. Build and Deploy to android tablet
4. Send Lock command to device

**Expected behavior**
Device should lock

**Desktop (please complete the following information):**
Ubuntu 16.04
Docker Environment

**Smartphone (please complete the following information):**
Lineage OS 14
Nexus 7 2013 Tablet

**Comment by rafaelje** [comment]
Thanks you are right we need check this value on our CI to verify the value
