### ISSUE TITLE
App deployment activity show only the last app ready to install

### ISSUE THREAD

**Issue by btry** [flyve-mdm/android-mdm-agent#579]
**Describe the bug**
I have several apps deployed with policies.

When the device receives the apk it notifies the user an app is ready to instal. 

When app A is ready i check the list of apps in the agent I see it.

A few seconds later app B is ready to isntall, the list shows only B

**To Reproduce**
1. create several app deployment policies fro a device
2. see the device ntify the user for an app
3. immediately open the agent and see the apk list ready to isntall
4. wait a few sseconds the app B is ready to installl
5. leave the mdm agent, open it again (splash screen must apear)
6. see app B on the list, and app A is lost

**Expected behavior**
the list shall show app A and app B

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rafaelje** [comment]
I found the problem here with the change of the install screen I need to move the Application save
