### ISSUE TITLE
Error deploying an app

### ISSUE THREAD

**Issue by abma** [flyve-mdm/android-mdm-agent#607]
Error on `applicationOnDevices `in activity log when deploying an app

**Describe the bug**
i've tried to deploy an app with Flyve MDM Agent version 2.0.0rc5 build 2618 from the fdroid store on a lineageos 14.1 device

**To Reproduce**

configure an app to deploy for the device. On the device i get the error

"Error on applicationOnDevices..."

**Expected behavior**
The app beeing installed.

ngrep output of the request made by the agent:
`
GET /glpi/apirest.php/initSession?user_token= HTTP/1.1
User-Agent: Dalvik/2.1.0 (Linux; U; Android 7.1.2; ASUS_Z00ED Build/NJH47F)
Host: 192.168.101.69..Connection: Keep-Alive
Accept-Encoding: gzip
`
and the response:
```

HTTP/1.1 400 Bad Request
Date: Wed, 17 Oct 2018 08:44:39 GMT
Server: Apache/2.4.25 (Debian)
Access-Control-Expose-Headers: content-type, content-range, accept-range
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache..Content-Length: 202..Connection: close
Content-Type: application/json; charset=UTF-8

["ERROR_LOGIN_PARAMETERS_MISSING","Parameter Login, Passwort oder Benutzertoken fehlt; zeige Dokumentation in Internet Browser ab http://192.168.101.69/glpi/apirest.php/#ERROR_LOGIN_PARAMETERS_MISSING"]
```

for some reason "user_token=" contains no value. ideas why / whats wrong?

**Comment by rafaelje** [comment]
The better and easy way that you can try FlyveMDM is with our demo site, please send us an email to this address contact@teclib.com

**Comment by abma** [comment]
> The better and easy way that you can try FlyveMDM is with our demo site, please send us an email to this address contact@teclib.com

how does this help to solve this issue?

do you need more information? The mobile has not internet connection its directly connected via wifi to an internal network.

**Comment by abma** [comment]
on the mobile in /data/data/org.flyve.mdm.agent/databases/flyve-mdm-db table mqtt, the value for userToken is empty. When manually set it to the value of the user:

```
adb shell
su
sqlite3 /data/data/org.flyve.mdm.agent/databases/flyve-mdm-db
update mqtt set value="<user token from the user>" where name='userToken';
.quit

```

it seems to work.
an idea why userToken is empty? What could be wrong with the enrollment / communication?

For testing purposes we don't use tls, maybe that could be the case as certificate + tls config is stored in this table, too?

**Comment by abma** [comment]
the line which very likely causing the problem was added with pull request #601
