### ISSUE TITLE
Possible MQTT multi-instantiation

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-mdm-agent#610]
Hi, @rafaelje 

We can see logs for multi-instantiation connections of the MQTT protocol.
We are debugging to provide to you more details.

**Comment by btry** [comment]
Ussing the commit from @farfou here are the results

after 2 or 3 minutes of execution after apk installation
![image](https://user-images.githubusercontent.com/14139801/47429821-c29e7c00-d797-11e8-9da3-fa365d5bcf5e.png)

when I open the main activity
![image](https://user-images.githubusercontent.com/14139801/47429847-d3e78880-d797-11e8-9f4c-b403f4b5e844.png)

tha app crashed very likely due to a "storm" of mqtt messages i noticed a few days ago

**Comment by rafaelje** [comment]
https://github.com/flyve-mdm/android-mdm-agent/blob/1c726bab355cfe726a7327baee83d2be3d46f563/app/src/main/java/org/flyve/mdm/agent/core/mqtt/MqttModel.java#L176 This code prevents a multiples instances of MQTT client, I add a counter and this is the result:

<img width="1027" alt="captura de pantalla 2018-10-30 a la s 11 46 10 a m" src="https://user-images.githubusercontent.com/4085091/47730871-717c0580-dc39-11e8-8a72-835629c7e7a6.png">

**Comment by farfou** [comment]
> [android-mdm-agent/app/src/main/java/org/flyve/mdm/agent/core/mqtt/MqttModel.java](https://github.com/flyve-mdm/android-mdm-agent/blob/1c726bab355cfe726a7327baee83d2be3d46f563/app/src/main/java/org/flyve/mdm/agent/core/mqtt/MqttModel.java#L176)
> 
> Line 176 in [1c726ba](/flyve-mdm/android-mdm-agent/commit/1c726bab355cfe726a7327baee83d2be3d46f563)
> 
>  if(client==null) { 
> This code prevents a multiples instances of MQTT client, I add a counter and this is the result:
> <img alt="captura de pantalla 2018-10-30 a la s 11 46 10 a m" width="1027" src="https://user-images.githubusercontent.com/4085091/47730871-717c0580-dc39-11e8-8a72-835629c7e7a6.png">

Maybe your code prevents from multiple instantiations of the client, inside the MqttModel class, but with the counters I added a few days ago (as shown in your log...), the MqttService onStartCommand may instantiate many MqttModel (don't know why yet. Android specs?), but in the end, maybe many MqttModel instances could be created, no ? So, in the end many clients.

More, inside the MqttModel, in my opinion, your code prevents from multiple "client" instantiation, right, but, if the same instance of the MqttModel is reused, maybe many "client.connect(options)" calls could be executed, no ?

**Comment by rafaelje** [comment]
The problem here is not with multiples instances of the mqtt client is the ability to connect many times to the same topic, mqtt can subscribe many times to the topic /0/fleet/64 and get many response from here
