### ISSUE TITLE
Issue deploying application via Flyve Plugin 

### ISSUE THREAD

**Issue by MsTsankur** [flyve-mdm/android-mdm-agent#615]
**Describe the bug**

When I deploy the .apk, my file is downloaded on my device, but it does not install the application. MDM Agent application pops with a white screen and "Installing application" at the bottom, but this screen never goes off. On the agent's page of GLPI plugin my task has the status "pending".

**To Reproduce**
Just deploying a file via Flyve GLPI's Plugin

**Expected behavior**
I expected the classic Android install pop up to appear.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
 - Mozilla Firefox

**Smartphone (please complete the following information):**
 - Device: Zebra TC56
 - OS: Android Nougat 7.1

**Additional context**
The aim of this manipulation is to push a new application on a fleet of 300 TC56 Devices.
The application used for this test weight 36Mo.

**Comment by btry** [comment]
Talk with @MsTsankur : 
- the device is responssive: we can switch to an other activity;
- if we tap the file from the filesystem, the app installs successfully

**Comment by MsTsankur** [comment]
By looking at adb log cat I didn't find any information about an installation sequence. I see the download sequence but nothing happens after this.

**Comment by rafaelje** [comment]
Hello @MsTsankur please check this PR https://github.com/flyve-mdm/android-mdm-agent/pull/616 has a new fix on application deploy policy

**Comment by rafaelje** [comment]
I test this issue and is working fine now but @MsTsankur please let me know how I can help you to test on your device
