### ISSUE TITLE
Wrong offline status notification

### ISSUE THREAD

**Issue by DIOHz0r** [flyve-mdm/android-mdm-agent#618]
**Describe the bug**
When the agent goes offline the MQTT message is published to the wrong topic. It is published to '
/Status/Online' also the format of the message has an invalid JSON string (no quoted strings).

**To Reproduce**
1. Go to MQTT tool like MQTTbox and subscribe to #
2. Turn off the device (Android emulator can be useful).

**Expected behavior**
A valid JSON string message like {"online": "false"} published to the topic '0/agent/{serial}/Status/Online'

**Screenshots**
![imagen](https://user-images.githubusercontent.com/1426313/47810928-dc513d80-dd1a-11e8-8074-77fd329087fb.png)

**Comment by btry** [comment]
This shoud be fixed by #611
