### ISSUE TITLE
Wipe doesn't delete /sdcard

### ISSUE THREAD

**Issue by abma** [flyve-mdm/android-mdm-agent#621]
**Describe the bug**
wiping a device doesn't delete /sdcard. i.e. images are not deleted!

**To Reproduce**
select device -> dangerous tasks -> wipe

**Expected behavior**
/sdcard deleted

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7
 - OS: LineageOS 14.1

**Comment by abma** [comment]
https://github.com/flyve-mdm/android-mdm-agent/blob/621c3488d24d04762c5e95b160566a38dd3cf944/app/src/main/java/org/flyve/mdm/agent/services/PoliciesDeviceManager.java#L144

DPM.wipeData(0);

according to https://developer.android.com/reference/android/app/admin/DevicePolicyManager#WIPE_EXTERNAL_STORAGE

wipeData should be called with WIPE_EXTERNAL_STORAGE which is 1

**Comment by rafaelje** [comment]
this issue is already done and merge
