### ISSUE TITLE
Deploy File or Apk not run

### ISSUE THREAD

**Issue by Greenstonetr** [flyve-mdm/android-mdm-agent#643]
Hi 
I am from Turkey.

SORRY My English.

My Flyve MDM Dashboard is not running correctly.

I cannot deploy a file or app  to Android Tablet.

There is some errors:

1-) From Android MQTT Error

![error-1](https://user-images.githubusercontent.com/43892434/49569577-60fc3080-f945-11e8-9f86-ec2158a4d44f.png)

2-) From Android Tablet Message Box

"Application Not Found in List of Installed Applications"

3-) Fusion Inventory Package Management Settings

![fusioninventory_package_management](https://user-images.githubusercontent.com/43892434/49569741-d5cf6a80-f945-11e8-809b-5e9a95165989.PNG)

4-) Fusion Inventory Deploy Mirror Servers

![deploy_mirror](https://user-images.githubusercontent.com/43892434/49569818-0fa07100-f946-11e8-9985-d2ae2037a5de.PNG)

My Linux Screen shoots

![linux](https://user-images.githubusercontent.com/43892434/49569883-38c10180-f946-11e8-9776-4dff6007787a.PNG)

Note:

Android Tablet Samsung SM P600

**Comment by ajsb85** [comment]
Duplicated https://github.com/flyve-mdm/web-mdm-dashboard/issues/1199

**Comment by ajsb85** [comment]
Hi, @btry & @rafaelje 
Looks like an issue with the MDM Agent.
So, I will keep the issue in this repository

**Comment by btry** [comment]
Hi @Greenstonetr 

To upload an apk to a device you must upload it via the UI provided by Flyve MDM. 
![image](https://user-images.githubusercontent.com/14139801/49636261-64092680-fa02-11e8-9330-3b9f9627965e.png)

Once done, you should wait for the automatic action which analyzes the new packages. Ut reads it to get some metadata. You may force its execution in the UI of GLPI too.

Next, apply a app deployment policy to a device or a fleet and select the apk.

No need to upload by hand an apk in /var/www/html or any other path.
No need to tune any Fusion Inventory setting, as it is not involved in this use case.

Based on the screenshots you shared it seems that the plugin works fine (the logs show the message to deploy an app). You might have a too old version of the mdm agent. Please, share a screenshot of the mdm agent, page "about".

**Comment by Greenstonetr** [comment]
Thanks for your answers. I solved this problem. Update Android agent apk files...

**Comment by shbharti** [comment]
> Hi @Greenstonetr
> 
> To upload an apk to a device you must upload it via the UI provided by Flyve MDM.
> ![image](https://user-images.githubusercontent.com/14139801/49636261-64092680-fa02-11e8-9330-3b9f9627965e.png)
> 
> Once done, you should wait for the automatic action which analyzes the new packages. Ut reads it to get some metadata. You may force its execution in the UI of GLPI too.
> 
> Next, apply a app deployment policy to a device or a fleet and select the apk.
> 
> No need to upload by hand an apk in /var/www/html or any other path.
> No need to tune any Fusion Inventory setting, as it is not involved in this use case.
> 
> Based on the screenshots you shared it seems that the plugin works fine (the logs show the message to deploy an app). You might have a too old version of the mdm agent. Please, share a screenshot of the mdm agent, page "about".

Hi @btry 

I did the same steps and can't see the apk in the Flyve mdm agent app under Activities>Applications

I am using version 2.0.0-rc.7, build 3238
![image](https://user-images.githubusercontent.com/16239757/83731784-b57e8a00-a668-11ea-804c-3977069bb152.png)

Looking forward for a quick reply

**Comment by stonebuzz** [comment]
Hi @shbharti 

can you test with develop branch ?

Best regards

**Comment by shbharti** [comment]
> Hi @shbharti
> 
> can you test with develop branch ?
> 
> Best regards

Hi @stonebuzz 

Yes. I did with the develop branch. Also, tried with some other branches as well. Nothing worked
