### ISSUE TITLE
TLS handshake issue with version 2.0.0rc6

### ISSUE THREAD

**Issue by iorfmer** [flyve-mdm/android-mdm-agent#649]
After device enrollment form, device enrolls correctly in the plugin, but application stays offline. We got this error in the application activity section:
```

org.flyve.mdm.agent.core.mqtt.MqttModel, showDetailError
(506) javax.net..ssl:SSLHandshakeException:
java.security.cert.CertPathValidationException: Trust anchor for certification path not found.
```
Same device works correctly with agent version 2.0.0rc5

Deice:Yuntab E706
Android 5.1
Android-mdm-agent 2.0.0rc6

**Comment by btry** [comment]
Hi 

There is very likely a misconfiguration of your certificates in Mosquitto. Mosquitto should probably send internediate CA certificates to the device to allow the mdm agent to build the complete trustchain from your certificate to a root CA.

check the chain witl openssl : openssl s_client <server:port>

**Comment by iorfmer** [comment]
Hi,

No there isn't. It is working with agent version 2.0.0rc5 and SSL certificates verified by connecting with OpenSSL .

Thanks.

**Comment by ajsb85** [comment]
Hi, @iorfmer 
Many issues related to ` Trust anchor for certification path not found.` https://github.com/flyve-mdm/android-mdm-agent/issues/328

You can go into github.com/flyve-mdm (the root of the org) and search issues for that.
