### ISSUE TITLE
Suffix for firebase-free build seems to break fdroid inclusion 

### ISSUE THREAD

**Issue by abma** [flyve-mdm/android-mdm-agent#671]
**Describe the bug**
I can only forward this bug as idk Details. I hope its undestandable:

F-Droid tagged flyve mdm with nosourcesince:

https://gitlab.com/fdroid/fdroiddata/issues/1497

->
"Includes Firebase libraries since 2.0.0-rc.7. There is a Firebase-free flavor
("mqtt"), but it adds a suffix to the application ID, so it basically
introduces a new app."

I hope i understood the information correctly: this means, that a mqtt build should be without "mqtt" suffix in the application ID.

https://github.com/flyve-mdm/android-mdm-agent/releases

**Expected behavior**
Flyve MDM 2.0.0-rc.7 should be available at fdroid.

**Comment by licaon-kter** [comment]
Already fixed as a new app: https://gitlab.com/fdroid/fdroiddata/merge_requests/4261

Or if upstream drops the suffix... (I'll remove the new app then)

**Comment by abma** [comment]
yeah, seems like this issue is more a question. Is the rename "final" or will it be reverted for the mqtt version?

**Comment by licaon-kter** [comment]
Nothing is final, ever. :)

It depends on what upstream wants and does.

**Comment by abma** [comment]
seems org.flyve.mdm.agent.mqtt will be used:
https://github.com/flyve-mdm/android-mdm-agent/commit/941286f0c17719312c0a1f539dcf8fbf870a86b0

:)
