### ISSUE TITLE
FCM not available in MQTT Beta channel version

### ISSUE THREAD

**Issue by jmpolvera** [flyve-mdm/android-mdm-agent#677]
**Describe the bug**
MDM android agent display a FCM not available error using MDM Android agent Beta channel while FCM is disabled in GLPI

"FCM service is not available"

**To Reproduce**
1. Send invitation from GLPI
2. Open Android beta channel mdm app
3. FiIl out first name, last name and email information in mdm agent
4. Click enroll

**Expected behavior**
Enroll device without FCM to be enabled in GLPI

**Smartphone (please complete the following information):**
 - OS: Android 6.0.1

[errorfcm.txt](https://github.com/flyve-mdm/android-mdm-agent/files/2841897/errorfcm.txt)

**Comment by stonebuzz** [comment]
Which version of FlyveMDM are you used ? 

FCM or MQTT ?

Best regards

**Comment by jmpolvera** [comment]
Sorry I dropped testing since no received response
