### ISSUE TITLE
RC7 Build for MQTT

### ISSUE THREAD

**Issue by Greenstonetr** [flyve-mdm/android-mdm-agent#687]
I want to run Agent software only with mqtt service. What kind of editing do I need in Android Studio?

org.flyve.mdm.agent_2018-12-17_205913-mqtt-release.apk   ---> source code ?

**Comment by ajsb85** [comment]
Here is the documentation to build the agent with the scripts:
https://git.io/fjUIu

**Comment by Greenstonetr** [comment]
I looked. But I don't understand. 
Can you add to releases  ---> mqtt_release

**Comment by abma** [comment]
@Greenstonetr 

you could try the fdroid build: https://f-droid.org/de/packages/org.flyve.mdm.agent.mqtt/

**Comment by Greenstonetr** [comment]
I builded. But that is FCM release.

**Comment by stonebuzz** [comment]
@Greenstonetr you need to change variant on AndroidStudio
and build app

![image](https://user-images.githubusercontent.com/7335054/69247142-3c2ab880-0baa-11ea-8770-a8e4729f1d0b.png)

Don't hesitate to test latest version of develop branch

Best regards
