### ISSUE TITLE
(205) - EXCEPTION_HTTP_Connection timed out

### ISSUE THREAD

**Issue by kageneck** [flyve-mdm/android-mdm-agent#690]
Describe the bug :
Once you try to enroll the device, appears the message like in the subject.

To Reproduce :
Open the App
Scan the QR code
Request permission
Creating inventory and session
See error

Expected behavior :
It should enroll the device.

**Comment by carmeloleonardi** [comment]
I also have the same problem when enroll the device

**Comment by joecizac** [comment]
@kageneck Why was this closed? You found a fix?
