### ISSUE TITLE
Issue updating application via Flyve MDM Agent

### ISSUE THREAD

**Issue by sebastienclement** [flyve-mdm/android-mdm-agent#699]
**Describe the bug**
After a first successfull apk deployment on a fleet, I did a new deployment with a new version of this apk. But when I tap to install this update nothing happens, just a white screen with "installing app.." but no install process.
If I tap the downloaded apk from the filesystem, the update occurs.
If I uninstall at first the old installed application on the device, I can install any of both version via Flyve MDM Agent.

**To Reproduce**
1. Deploy a new version of an apk already install on the fleet
2. Tap on "Ready to update" in Flyve MDM Agent / Activity / Applications
3. A white screen appears and no installation process

**Expected behavior**
an installation of the update without uninstall at first the old version.

**Screenshots**
![Screenshot_20190719-110020 1](https://user-images.githubusercontent.com/32647279/61523454-b12b8d00-aa14-11e9-858c-be01692fafde.png)
![Screenshot_20190719-110025 1](https://user-images.githubusercontent.com/32647279/61523469-bbe62200-aa14-11e9-80ab-26a74a5023e2.png)

**Desktop :**
 - OS: Windows 10 Pro 1803
 - Browser Firefox 68.0

**Smartphone (please complete the following information):**
 - Device: Athesi E5
 - OS: Android 7.0

**Additional context**

**Comment by sebastienclement** [comment]
Hello,

anyone to help me or give me a trick ?

**Comment by stonebuzz** [comment]
Hi sebastienclement ,

can you test the develop branch ?

improvements have been made for apk management.

Best regards

**Comment by sebastienclement** [comment]
Hi stonebuzz,

thank you for your reply.

I would like to test it but I can't. When I want to build the apk from the develop branch I get the same message error that [#670](https://github.com/flyve-mdm/android-mdm-agent/issues/670) issue.

Maybe I missed something ?

Best regards,

**Comment by stonebuzz** [comment]
Hi @sebastienclement, i can't reproduce anymore this problem, can you give step to reproduce ?
How do you launch the build ?
Which module and build variant are you used ?

Thanks.

**Comment by sebastienclement** [comment]
Hi @stonebuzz, 

I figured out that and it's no longer a problem.

I tested the develop branch (build 3715) and I noticed an improvement compared to the build 3238 in the app.
In _Activity_ section, _Policies_ tab, now I have my policies history that I didn't have before. 

But I faced to another problem. When I deploy my first app, everything is alright. 
But at the second deployment (new app version to make an update) no apk is transferred to the device. I'm well notified "Pending to install" and in the _Applications_ tab the new line is totally identical as the first one. Same Version Code and Version Name are displayed whereas it shouldn't.

I just notice that if I change the application name of the app I want to deploy on different versions, there is a transfer of the apk and the correct informations display in the _Applications_ tab.
It also display the message "Ready to update" but I get the same blank page with no process behind.

I'm available for more infos if you want.
Thanks

**Comment by stonebuzz** [comment]
Hi sebastienclement, thanks for feedback 

I'm looking at  ASAP.

Best regards

**Comment by stonebuzz** [comment]
Hi @sebastienclement , can you provide me 

can you provide me screenshots of the package configuration on GLPI?

Like this 

![image](https://user-images.githubusercontent.com/7335054/69059271-79117680-0a15-11ea-9b34-8f2499659f73.png)

Best regards

**Comment by sebastienclement** [comment]
Hi @stonebuzz , here is the package's screenshot.

![flyve-mdm-package-config](https://user-images.githubusercontent.com/32647279/69126336-419fda00-0aa8-11ea-9302-3ac3f6d95994.JPG)

Best regards

**Comment by stonebuzz** [comment]
Hello, 
rather than creating a new task to deploy the new version of the package, can you simply modify the existing package by uploading a recent apk, FlyveMDM plugin should send a notification to the agent with the new version.

Best regards

**Comment by stonebuzz** [comment]
Hi @sebastienclement , 

I just updated the branch develop, to fix your problem with package updates.

I also confirm that it is necessary to update the package rather than create a new task on an agent. (don't forget to start the ParseApplication task right after)

Thus, FlyveMDM plugin send a notification to the agent to update the package.

Can you try latest version of develop branch ?

Best regards

**Comment by sebastienclement** [comment]
Hi @stonebuzz,

it just works perfectly (build 3799). Thank you.

I proceeded as you said, an updating rather than creating a new task.

Maybe it's normal, I just noticed (cf screenshot) that _Version Name_ information doesn't update.
To test, in my case I deployed first 0.5.2, then updated 0.5.3, 0.5.4 and 0.5.5. Only _Version Code_ information succesfully updated. 

![Screenshot_20191125-094159 1](https://user-images.githubusercontent.com/32647279/69525625-d141fe80-0f68-11ea-94bd-f70b8adb6d29.png)

But everything work fine for me.

Best regards

**Comment by stonebuzz** [comment]
yes its an issue with reload fragment, of you go to home activity then return to app list, you will see the version name change.

Best regards

**Comment by stonebuzz** [comment]
Hi @sebastienclement 

I opened a issue for this problem.

Best regards

**Comment by sebastienclement** [comment]
Thanks again @stonebuzz
