### ISSUE TITLE
REBOOT in ANDROID MDM

### ISSUE THREAD

**Issue by ShriChanaveer** [flyve-mdm/android-mdm-agent#774]
Hi Team ,
I am unable to REBOOT the system in rooted Android Device also below  is the error

AndroidPolicies.reboot  (AndroidPolicies.java:144)
FlyveLog.e  (FlyveLog.java:91)
Neither user 10157 nor current process has android.permission.REBOOT

**Comment by stonebuzz** [comment]
Hi @ShriChanaveer 

can you give me more infromations 

apk version
build version (mqtt : FCM)
android version
Manufacturer etc ...

Best regards

**Comment by ShriChanaveer** [comment]
Hi Team,
I have cloned mdmd-agent code from the github and same web portal also
cloned and we have done our own setup also and we are able to perform all
the functionalities apart from
1)device lock
2) reboot

Note :Device is rooted and granted super user permission for mdm-agent

Kindly find device specification

**Comment by stonebuzz** [comment]
Hi @ShriChanaveer 

reboot permission is already added to FlyveMDM agent
-> https://github.com/flyve-mdm/android-mdm-agent/blob/develop/app/src/main/AndroidManifest.xml#L56
But is only granted when agent is installed as system apps (priv_app folder)

See this "How To" -> http://flyve.org/android-mdm-agent/howtos/installation

Best regards

**Comment by ShriChanaveer** [comment]
Thanks Team,

I am able to reboot now 😊
