### ISSUE TITLE
Inventory misformed XML Entry WIFI_BSSID

### ISSUE THREAD

**Issue by aniwel** [flyve-mdm/android-mdm-agent#775]
Hello,
i get the following misformed entry in a inventory an a Huawei mobile.
Branch: develop
The enrollment stops with an XML-error
 
    <NETWORKS>
      <DESCRIPTION>N/A</DESCRIPTION>
      <DRIVER>WIFI</DRIVER>
      <IPADDRESS>0.0.0.0</IPADDRESS>
      <IPADDRESS6>fe80::xxxx:xxxx:xxxx:xxxx</IPADDRESS6>
      <IPDHCP>192.168.xxx.xxx</IPDHCP>
      <IPGATEWAY>0.0.0.0</IPGATEWAY>
      <IPMASK>0.0.0.0</IPMASK>
      <IPMASK6>ffff:ffff:ffff:ffff::</IPMASK6>
      <IPSUBNET>0.0.0.0</IPSUBNET>
      <IPSUBNET6>fe80::</IPSUBNET6>
      <MACADDR>DC:72:9B:xx:xx:xx</MACADDR>
      <SPEED>-1</SPEED>
      <STATUS>N/A</STATUS>
      <TYPE>WIFI</TYPE>
      <WIFI_BSSID><unknown ssid></WIFI_BSSID>
      <WIFI_SSID>02:00:00:00:00:00</WIFI_SSID>
    </NETWORKS>

Thanks,

**Comment by stonebuzz** [comment]
Hi @aniwel 

We are aware of this problem and are currently working on it.

The problem should be solved soon.

kind regards

**Comment by aniwel** [comment]
Thanks for your quick reply @stonebuzz

**Comment by stonebuzz** [comment]
@aniwel  can you test develop branch =)

inventory library has been update by this PR -> #776 

Best regards

**Comment by aniwel** [comment]
I won't have access to the huawei phone until tomorrow. I'll test it then.
Best regards

**Comment by aniwel** [comment]
Now it works
Thanks  @stonebuzz
