### ISSUE TITLE
Request Permission : result with "404 Not Found"

### ISSUE THREAD

**Issue by Alendrill** [flyve-mdm/android-mdm-agent#785]
**Describe the bug**
During the enrollment process, when clicking on "Request information" I obtain : "Wrong information ... 404 Not Found"

**To Reproduce**
1. Invite a Agent by mail
2. Flash the QR Code
3. Click on "Request permission"

**Expected behavior**
The agent should be enrolled in Flyve MDM

**Screenshots**
![image](https://user-images.githubusercontent.com/59729373/72148535-6118fc00-33a1-11ea-8016-040f046487f6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10
 - OS: Q Android 10.0 api 29
 - Browser Chrome

**Additional context**
Full error : "(206) - Wrong information, data: <html><head><title>404 Not Found</title><body bgcolor="white">..."

**Comment by stonebuzz** [comment]
Hi @Alendrill ,

Can you check GLPI configuration ?
Have you correctly set the "url_base_API" here ?


![image](https://user-images.githubusercontent.com/7335054/72148837-0fbd3c80-33a2-11ea-8c00-6151f3751350.png)

Best regards

**Comment by Alendrill** [comment]
> er

Yes, I think it is correctly configured : 
![image](https://user-images.githubusercontent.com/59729373/72149258-07193600-33a3-11ea-8769-687997338cd2.png)

**Comment by stonebuzz** [comment]
What do you get with this URL in the browser?

**Comment by stonebuzz** [comment]
it's a local GLPI ?
Phone is on same WIFI ?
did you use an IP for the API URL

Best regards

**Comment by Alendrill** [comment]
> What do you get with this URL in the browser?

If copy/paste it on my search bar, I got this : 
![image](https://user-images.githubusercontent.com/59729373/72149722-0fbe3c00-33a4-11ea-83ae-a08b20ded971.png)

But, when I click on "Documentation en ligne de l'API" the link redirect me to the same link adding "/" at the end, see : 
![image](https://user-images.githubusercontent.com/59729373/72149856-5b70e580-33a4-11ea-8ac1-0977eaed8441.png)

**Comment by stonebuzz** [comment]
ok isee, you missed "inc" folder 

 try with http://192.168.0.245/glpi/inc/apirest.php

if it's ok

update glpi API configuration 
clean / recreate  invitation  
retry with FlyveMDM

Best regards

**Comment by Alendrill** [comment]
> it's a local GLPI ? It's not a local GLPI but for test i use ip address for no specific reason.
> Phone is on same WIFI ? Yeah, it's connected on the same WiFi
> did you use an IP for the API URL ? Yeah I uses an ip in the API URL
> 
> Best regards


I tried to access the link you said, but i have a "403 Forbidden". Furthermore, when I look on my web server I have any file "apirest.php" in the "inc" folder.

**Comment by stonebuzz** [comment]
yes because your you have configured your API to access on it with login, can you disable connection with login, just keep external  token,

check if your user have a token api in personal preferences 

![image](https://user-images.githubusercontent.com/7335054/72154055-de4b6d80-33af-11ea-9eeb-b064c66c407d.png)

then check API client configuration here
![image](https://user-images.githubusercontent.com/7335054/72154100-0935c180-33b0-11ea-8400-8fca7ba48c83.png)

by default API allow only localhost, update client API with device phne IP

**Comment by Alendrill** [comment]
So, I kept only the connection by external token. But it remain the same.

My user have an external token :
![image](https://user-images.githubusercontent.com/59729373/72155243-fffa2400-33b2-11ea-86e6-08d1380c3667.png)

And in the API client, I have a full access from localhost (as you said) and another account for remote connection : 
![image](https://user-images.githubusercontent.com/59729373/72155299-20c27980-33b3-11ea-9b53-95c36d6f8b32.png)


Conclusion : anything changed, I still have the same error 403. Any change for the mobile phone

**Comment by stonebuzz** [comment]
Sorry I made a mistake..
Your URL http://192.168.0.245/glpi/apirest.php should be fine now with your configuration

Can you just show me your client configuration for device

Best regards

**Comment by Alendrill** [comment]
This one ?
![image](https://user-images.githubusercontent.com/59729373/72158361-5585ff00-33ba-11ea-8713-ec4c4848d4e5.png)

**Comment by stonebuzz** [comment]
yes, seem's good.

After change API url in GLPI configuration can you retry an enrollment from scratch

- clean all invitation / documents /agents
- create invitation
- try to enroll device.

**Comment by Alendrill** [comment]
I saw you coming and tried already. But no, it's doesn't work : 404 error

**Comment by Alendrill** [comment]
The link is correct, but when I try it from this button : 
![image](https://user-images.githubusercontent.com/59729373/72158745-389dfb80-33bb-11ea-92b8-57895d5bd8ee.png)

It add "/" and lead to the 404 error page

**Comment by stonebuzz** [comment]
i cannot reproduce, if i clic on link i've got

![image](https://user-images.githubusercontent.com/7335054/72159599-ff668b00-33bc-11ea-8a37-1441f7cb78c9.png)

with or withou slash at end of URL

what is your web server ? Apache2 / Nginx ?

**Comment by Alendrill** [comment]
My webserver is NGINX.

I tried in curl, and I have an error when it call "apirest.php/initSession"

**Comment by stonebuzz** [comment]
can you show me your nginx conf

Have you got some GLPI errors in log files  ?

**Comment by Alendrill** [comment]
Finaly, I converted NGINX into an Apache Web Server and it work far better.

**Comment by Alendrill** [comment]
I don't have understand the source of the problem, but it was a conflict with PHP in the config of NGINX.
