### ISSUE TITLE
(211) - value EXCEPTION_HTTP_timeout of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by shbharti** [flyve-mdm/android-mdm-agent#792]
**Describe the bug**
When trying to enroll my mobile (Redmi Note 5 Pro, Android: 9) I get the following error messages :
**(211) - value EXCEPTION_HTTP_timeout of type java.lang.String cannot be converted to JSONObject**

**To Reproduce**
1. Opened the deep link in the Flyve MDM Agent
2. Click on 'Enroll device'
3. Click on 'REQUEST PERMISSION'
4. Accept All permissions request
5. Click on 'Continue'
6. Filled the form. Entered first name, last name, same mail ID as registered, contact number and then click on 'Right' icon (on the top right)
7. Found popup of 'Enrollment in Process' for a long time.
8. Then got error:
'(211) - value EXCEPTION_HTTP_timeout of type java.lang.String cannot be converted to JSONObject'

**Screenshots**
![image](https://user-images.githubusercontent.com/16239757/83485761-58969e80-a4c5-11ea-8dc5-409bcd5f71ec.png)

**Smartphone (please complete the following information):**
![image](https://user-images.githubusercontent.com/16239757/83485890-9dbad080-a4c5-11ea-9c3e-fe39bbfe94de.png)

**Additional context**
Can you please help me? Look forward for a quick response

**Comment by stonebuzz** [comment]
Hi @shbharti 

When you try to enroll your mobile are you on WiFi ?
 Is GLPI accessible from the internet ?

Best regards

**Comment by shbharti** [comment]
Hi @stonebuzz 
Thanks for responding :)
This is resolved by correcting IP configurations in the "Message Queue"
