### ISSUE TITLE
Nothing happens after user information was send

### ISSUE THREAD

**Issue by Izanagi52** [flyve-mdm/android-mdm-agent#797]
**Describe the bug**
When I send the Enrollement form, I have this message :
"(210) - XML has been imported succesfully!"
And nothing happens after this.

**To Reproduce**
I have build the FCMdebug version of the latest development branch (2.0.0-rc.7.3882), with my google-services.json (on app folder) of a new Firebase Project made for this.
I have set the server key token in glpi plugin and enabled Firebase Cloud Messaging.

1. Install the APK on the phone
2. Send invitation from glpi
3. Click on the link directly on the phone.
4. Give all the authorization asked by MDM Agent.
5. Complete with correct mail and name the form.
6. Validate, and after a short time, "(210) - XML has been imported succesfully!"" and nothing else.

In GLPI, I can see invitation done, the FusionInventory Agent, and the Computer corresponding to my phone, but there is no Flyve MDM Agent.

**Screenshots**
![Screenshot_20200611_163838_org flyve mdm agent (2)](https://user-images.githubusercontent.com/21294450/84402838-46270e00-ac05-11ea-864f-93208e43a2de.jpg)
![Screenshot_20200611_164523_com android settings (2)](https://user-images.githubusercontent.com/21294450/84402867-50e1a300-ac05-11ea-8058-274e9515dc1b.jpg)

**Smartphone (please complete the following information):**
 - Device: Huawei P Smart 2019 (POT-LX1)
 - OS: Android 10
 - Browser: Chrome
 - Version: 83.0.4103.10

**Additional context**
Sorry for my bad English, I'm french.

**Comment by stonebuzz** [comment]
hi @Izanagi52 

can you retry and provide logcat ?

Best regards

**Comment by Izanagi52** [comment]
I find the problem today.... It was just a problem of entity in GLPI....
So now it works, I can go to the screen after enrollment.
But now, GLPI have a timeout if I try to ping, geolocate or inventory in the agent GLPI page (even with app open on the phone).
The phone is always shown Online, even he is shutdown.

And in the app, i see nothing in policies, app, etc (but I have fcm message in log)

![fcm_log](https://user-images.githubusercontent.com/21294450/85028252-1fc02000-b17b-11ea-9aab-0b00d773e976.jpg)


Maybe I haven't build the app correctly, where do I need to place my google-service.json file ?
I have it in the root of "app" folder.
Do I need to replace json in "app/src/fcm", "app/src/main" and "app/src/mqtt" ?
I'm confused with this.

**Comment by Izanagi52** [comment]
If it can help, ping works, but only if I click ping on GLPI, then, while glpi is loading, I open Flyve MDM on my Android.
And only ping is working.

**Comment by stonebuzz** [comment]
Since version 9 of android, the MQTT version of the agent has to be in foreground due to limitation of background service introduced by google.

For information, we are currently working on the FCM version, and the MQTT version is stopped because of this limitation. 

For Android >= 9 please use FCM version of agent.

Best regards

**Comment by Izanagi52** [comment]
Yes, it's what I do...
I have build my own FCM version, since we need to use our google-service.json file, to link it to our Firebase project (correct ?).
But it doesn't work correctly.

And the ping doesn't work when FlyveMDM is in foreground, but when I launch FlyveMDM at the same time where GLPI load the ping request.
If the app is already in foreground when I launch ping request, it doesn't work.

**Comment by tonius85** [comment]
Hi,

I have been looking for 2 days,

Google does not explain where to position the .json correctly.
You have to replace the existing config in src/fcm / for it to work ;)

**Comment by Izanagi52** [comment]
Thanks!
It's working now!
(Now, I need to make it work with another entity than the default, but it's another problem)
