### ISSUE TITLE
Need Information - FCM Related

### ISSUE THREAD

**Issue by kaleemlab** [flyve-mdm/android-mdm-agent#805]
**I have a query related to FCM Android Agent.**

I'm working on the Flyve Android MDM Agent Project and making proper documentation for the complete setup for both GLPI+INVENTORY+AGENT.

Right now I'm trying to draw a sketch/flow diagram of the process of how FCM works in an android agent... in shot trying to understand the purpose of FCM (Token when a user scans QR Code, what happens in the background, similarly what's the difference between FCM and MQTT specifically in this project)
**Queries:**

**1 -**  What the process happens in the background when the user scans the QR Code (Enrollment in FCM)?
**2 -** Is there any data stores in FCM?
**3 -** What's the core difference between FCM and MQTT specifically in this project?
**4 -** Is data secure on FCM? 

My end product is to draw a proper pictorial representation of this complete process with FCM how user enrolls and what happens in the background.

Thanks.

**Comment by stonebuzz** [comment]
Hi @kaleemlab 

check this

https://flyvemdm-doc.readthedocs.io/en/latest/contribute/diagrams.html#enrollment-fcm

Best regards
